name: Dns-secondary-operator integration tests

on:
  pull_request:
    paths:
      - 'dns-secondary-operator/charmcraft.yaml'
      - 'dns-secondary-operator/lib/**'
      - 'dns-secondary-operator/pyproject.toml'
      - 'dns-secondary-operator/requirements.txt'
      - 'dns-secondary-operator/src/**'
      - 'dns-secondary-operator/tests/**'
      - 'dns-secondary-operator/tox.ini'
      - '.github/workflows/integration-test-dns-secondary-operator.yaml'
  push:
    branches:
      - main

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
      juju-channel: 4.0/stable
      provider: lxd
      working-directory: ./dns-secondary-operator
