name: Dns-secondary-operator tests

on:
  pull_request:
    paths:
      - 'dns-secondary-operator/charmcraft.yaml'
      - 'dns-secondary-operator/lib/**'
      - 'dns-secondary-operator/pyproject.toml'
      - 'dns-secondary-operator/requirements.txt'
      - 'dns-secondary-operator/src/**'
      - 'dns-secondary-operator/tests/**'
      - 'dns-secondary-operator/tox.ini'
      - '.github/workflows/unit-test-dns-secondary-operator.yaml'
  push:
    branches:
      - main

jobs:
  unit-tests:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      self-hosted-runner: false
      self-hosted-runner-label: "edge"
      working-directory: ./dns-secondary-operator
      require-check-lib: false
